### ISSUE TITLE
wsl-vpnkit interferes with and freezes python / pip ?

### ISSUE THREAD

**Issue by np-8** [sakai135/wsl-vpnkit#185]
Running Ubuntu 20.04.5 LTS on WSL2, using python 3.8.10 and wsl-vpnkit v0.3.8.

I had this strange problem. When the wsl-vpnkit distro (and service) was running, commands like `python -m pip uninstall <package>` and `python -m pip list` got frozen. Here is Traceback for `python -m pip list` (after pressing Ctrl-C since the program was not responding):

<details>

<summary><b>Click to see Traceback</b></summary>

```python
niko@MYMACHINE:~/code/somerepo$ python -m pip list
^CTraceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/niko/.local/lib/python3.8/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/home/niko/.local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 68, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/niko/.local/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 114, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/niko/.local/lib/python3.8/site-packages/pip/_internal/commands/list.py", line 9, in <module>
    from pip._internal.cli.req_command import IndexGroupCommand
  File "/home/niko/.local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 20, in <module>
    from pip._internal.index.collector import LinkCollector
  File "/home/niko/.local/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 39, in <module>
    from pip._internal.network.session import PipSession
  File "/home/niko/.local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 43, in <module>
    from pip._internal.network.auth import MultiDomainBasicAuth
  File "/home/niko/.local/lib/python3.8/site-packages/pip/_internal/network/auth.py", line 29, in <module>
    import keyring
  File "/usr/lib/python3/dist-packages/keyring/__init__.py", line 3, in <module>
    from .core import (
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 189, in <module>
    init_backend()
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 93, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/lib/python3/dist-packages/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/keyring/backend.py", line 210, in get_all_keyring
    return list(rings)
  File "/usr/lib/python3/dist-packages/keyring/util/__init__.py", line 31, in suppress_exceptions
    for callable in callables:
  File "/usr/lib/python3/dist-packages/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python3/dist-packages/keyring/backend.py", line 67, in viable
    cls.priority
  File "/usr/lib/python3/dist-packages/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python3/dist-packages/keyring/backends/SecretService.py", line 34, in priority
    bus = secretstorage.dbus_init()
  File "/usr/lib/python3/dist-packages/secretstorage/__init__.py", line 47, in dbus_init
    return dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/exceptions.py", line 47, in __init__
    def __init__(self, *args, **kwargs):
KeyboardInterrupt
```
</details>

The same `python -m pip list` command worked *immediately* after I ran `wsl -t wsl-vpnkit` on Powershell. 

#### Repeatability of the problem
Unfortunately, I could not reproduce the same error yet. I did experience the problem yet only with the system level `python`, and not with ones in a virtual environment. Maybe this has something to do with the order of what was executed first? 

Anyway, leaving this one out in case someone else faces this.

**Edit**: Might be also caused because of set `DISPLAY` environmental variable. See: [Issue 7883 on pypa/pip](https://github.com/pypa/pip/issues/7883#issuecomment-852102601). Not sure why would `wsl -t wsl-vpnkit` fix it, though.

**Comment by sakai135** [comment]
Thanks, it might be helpful also have the `wsl.exe --version` and logs from wsl-vpnkit, if any. If you are able to reproduce it later, check if other processes can access the network while pip is hanging.

**Comment by sakai135** [comment]
Closing due to inactivity.
